;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; 
; Author : Gargar			                                            ; 
; Date : March 11, 2018                                                             ; 
; Version: 1                                                                        ; 
; Title: Main configuration codes						    ; 
;                                                                                   ; 
; Description:	Includes all codes used for initialization different modules 	    ; 
;									  	    ; 
;                                                                                   ; 
; Modules incl.:								    ;
;   Interrupt									    ;
;   UART									    ;
;   LCD (16x2)									    ;
;   Keypad (4x3) : Soon							    ;
;   5ms delay									    ;
;                                                                                   ; 
;                                                                                   ;  
;                                                                                   ;  
;                                                                                   ;  
;                                                                                   ;  
;                                                                                   ; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; 



    
END